# Generated by Django 3.1.3 on 2020-11-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_contact_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
