# Generated by Django 3.1.3 on 2020-11-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_remove_contact_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(default=1.0),
            preserve_default=False,
        ),
    ]
