# Generated by Django 3.1.3 on 2020-11-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogApp', '0002_auto_20201116_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
