# Generated by Django 3.1.3 on 2020-11-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogApp', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
